version: "3.8"
name: digital_maturity

services:
  django:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: django
    command: python3 -m gunicorn digitalmaturity.wsgi --reload
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: --bind=0.0.0.0:8000 --workers=${GUNICORN_WORKERS}
      CSRF_TRUSTED_ORIGINS: ${PROTO}://0.0.0.0:${PORT} ${PROTO}://127.0.0.1:${PORT} ${PROTO}://192.168.0.21:${PORT} ${PROTO}://localhost:${PORT}
    depends_on:
      - postgres_db

  postgres_db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    env_file:
      - .env
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "${PORT}:80"
    depends_on:
      - django

volumes:
  pgdata:
  static_volume: