# Generated by Django 4.1.4 on 2023-05-03 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digmaturityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Респондент', 'verbose_name_plural': 'Респонденты'},
        ),
        migrations.AlterModelOptions(
            name='secretcode',
            options={'verbose_name': 'Секретный код', 'verbose_name_plural': 'Секретные коды'},
        ),
        migrations.AddField(
            model_name='question',
            name='subfactor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digmaturityapp.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.FloatField(verbose_name='Стоимость ответа'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='block',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(max_length=127, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='question',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digmaturityapp.block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='answers',
            field=models.ManyToManyField(to='digmaturityapp.answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='first_name',
            field=models.CharField(max_length=127, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='gender',
            field=models.CharField(max_length=63, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='patronymic',
            field=models.CharField(max_length=127, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digmaturityapp.post', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='second_name',
            field=models.CharField(max_length=127, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='secret_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digmaturityapp.secretcode', verbose_name='Секретный код'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digmaturityapp.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='secretcode',
            name='secret',
            field=models.CharField(max_length=63, verbose_name='Код'),
        ),
    ]
