# Generated by Django 4.1.4 on 2023-05-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digmaturityapp', '0003_alter_secretcode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='post_id',
        ),
    ]
