# Generated by Django 4.1.4 on 2023-05-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digmaturityapp', '0004_remove_respondent_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='age',
        ),
    ]
